local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 1.0
   publish_frequency: 1.0
   width: 70.0
   height: 70.0
   resolution: 0.5
   static_map: false
   rolling_window: true
